#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run build
# git add -f dist
# git commit -m "deploy"
# git subtree split --prefix dist -b gh-pages
# git push -f origin gh-pages:gh-pages
# git branch -D gh-pages
# git reset --soft HEAD~1